### ISSUE TITLE
Inference issue

### ISSUE THREAD

**Issue by dobrosketchkun** [keonlee9420/PortaSpeech#11]
Basically, I tried to run it in the Google Colab

1st cell

```python
%cd /content/
!git clone https://github.com/keonlee9420/PortaSpeech
%cd /content/PortaSpeech/
!pip install -r /content/PortaSpeech/requirements.txt
```

2nd

```python
id_big = '1VTotGmE42a19bevwgQ9mhPkXzQvKzl8q'
id_small = '1Y0IGlc4zJ7XN5sh4aPWLTeQ80D9ZhfbB'

!mkdir /content/PortaSpeech/output/
!mkdir /content/PortaSpeech/output/ckpt/
!mkdir /content/PortaSpeech/output/ckpt/DATASET/
%cd /content/PortaSpeech/output/ckpt/DATASET/
!gdown --id $id_big 
!gdown --id $id_small 
%cd /content/PortaSpeech
```

3rd

```python
%cd /content/PortaSpeech
!python3 synthesize.py --text "Moved to Site-19 1993. Origin is as of yet unknown. It is constructed from concrete and rebar with traces of Krylon brand spray paint." \
                        --restore_step 125000 --mode single --dataset DATASET
```

and this is what I've got:

```python
/content/PortaSpeech
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package cmudict to /root/nltk_data...
[nltk_data]   Unzipping corpora/cmudict.zip.
2021-10-26 10:57:51.803863: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "synthesize.py", line 138, in <module>
    args.dataset)
  File "/content/PortaSpeech/utils/tools.py", line 19, in get_configs_of
    os.path.join(config_dir, "preprocess.yaml"), "r"), Loader=yaml.FullLoader)
FileNotFoundError: [Errno 2] No such file or directory: './config/DATASET/preprocess.yaml'
```

What this 'preprocess.yaml'  is exactly?

**Comment by keonlee9420** [comment]
Close due to inactivity.
